# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Theme settings
#
# theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "contrast" # see https://mmistakes.github.io/minimal-mistakes/docs/skins/
# Possible values are: "default", "air", "contrast", "dark", "dusk", "light", "midnight", "modern", "solarized-dark", "solarized-light"

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: bobbie-hill.tech
subtitle: (Barbara Allen Hill)
name: Barbara A Hill
email: hill.barbara.a@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Engineering Leader | Senior Software Engineer | Product Management & Technical Leadership | DevOps | Building High-Performing Teams
github_username: bahill
locale: en_US
url: "https://bobbie-hill.tech" # the base hostname & protocol for your site
repository: "bahill/bobbie-hill.tech" # the GitHub repository of your site
search: false
enable_copy_code_button: true
atom_feed:
  hide: true
social:
  type:  Person # Person or Organization (defaults to Person)
  name:  # If the user or organization name differs from the site's name
  links:
    - "https://www.linkedin.com/in/barbara-a-hill"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Barbara (Bobbie) Hill"
  avatar : "/assets/images/BobbieHill_color_sqCrop.jpg"
  bio    : "I bring a human-centric approach to technology leadership, blending deep technical expertise with a passion for building collaborative, high-performing teams.""
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/barbara-a-hill"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bahill"
   
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/barbara-a-hill"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bahill"
  since: "2025"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
